* The Game
  $game is a massive multiplayer space exploration game where the
  player don't interact directly, but writes his own programs
  ('Agents') to control the entities in the game.

  These entities can be spaceships, planets, factories, trading posts,
  and whatever you can imagine.

* Space
  Space is divided into sectors. Every sector is a cube of not yet
  specified size. Transition is seamless. If you cross the border to a
  adjacent sector you get a message that you just entered it.

** Movement
   Every sector is a world agent (called 'sector agent'). The sector
   agent is responsible for the movement of all ships in it. It also
   notifies the agent of an adjacent sector if a ship is about to
   cross the border to it.

   When a ship wants to move, it signalizes its current sector agent
   that it fired its engines, telling him its current course. The
   sector agent acknowledges this, and answers with the estimated time
   of arrival (ETA).

   When the journey goes as expected, the sector agent signalizes the
   ship when it arrives at the destination. If the ship crosses the
   border to the next sector, it gets notified and the sector agent of
   the new sector notifies when the ship arrives at its destination.

* Planets
* Communication
  All between player controlles entities goes over the subspace. The
  subspace is a omnipresent physical dimension above our normal
  dimensions.

  Space and time isn't the same as in our dimension, therefore
  communication works instantly over vast (but limited) distances.

  Messages can be broadcasted without a direct target or entities can
  communicate directly with each other. The latter is always encrypted
  and is guaranteed to be private.

* Ships
* The Mighty Garbage Compiler
  - Like the strip in Star Trek which is the entrance into the Nexus?
